"""empty message

Revision ID: 30b6c7298528
Revises: 
Create Date: 2023-10-28 10:07:43.483682

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '30b6c7298528'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ofertas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prestamista', sa.String(length=50), nullable=False),
    sa.Column('montoOfrecido', sa.Text(), nullable=False),
    sa.Column('interesOferta', sa.Text(), nullable=False),
    sa.Column('tiempoPrestamo', sa.Text(), nullable=False),
    sa.Column('solicitud_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['solicitud_id'], ['solicitudes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('solicitudes', schema=None) as batch_op:
        batch_op.alter_column('edad',
               existing_type=mysql.MEDIUMTEXT(),
               type_=sa.Text(),
               existing_nullable=False)
        batch_op.alter_column('ingresos',
               existing_type=mysql.MEDIUMTEXT(),
               type_=sa.Text(),
               existing_nullable=False)
        batch_op.alter_column('historial_id',
               existing_type=mysql.MEDIUMTEXT(),
               type_=sa.Text(),
               existing_nullable=False)
        batch_op.alter_column('monto',
               existing_type=mysql.MEDIUMTEXT(),
               type_=sa.Text(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('solicitudes', schema=None) as batch_op:
        batch_op.alter_column('monto',
               existing_type=sa.Text(),
               type_=mysql.MEDIUMTEXT(),
               existing_nullable=False)
        batch_op.alter_column('historial_id',
               existing_type=sa.Text(),
               type_=mysql.MEDIUMTEXT(),
               existing_nullable=False)
        batch_op.alter_column('ingresos',
               existing_type=sa.Text(),
               type_=mysql.MEDIUMTEXT(),
               existing_nullable=False)
        batch_op.alter_column('edad',
               existing_type=sa.Text(),
               type_=mysql.MEDIUMTEXT(),
               existing_nullable=False)

    op.drop_table('ofertas')
    # ### end Alembic commands ###
